### ISSUE TITLE
#3 카카오 인증하기 오류

### ISSUE THREAD

**Issue by joonyy** [joonyy/SNS_Service#3]
#1 
카카오 간편로그인 기능 사용하여 로그인 시 다음과 같은 에러 발생
---
Validation error
Error
    at Query.run (/Users/kimjoonyoung/SNS_Service/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)
    at /Users/kimjoonyoung/SNS_Service/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MySQLQueryInterface.insert (/Users/kimjoonyoung/SNS_Service/node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)
    at async User.save (/Users/kimjoonyoung/SNS_Service/node_modules/sequelize/lib/model.js:2490:35)
    at async User.create (/Users/kimjoonyoung/SNS_Service/node_modules/sequelize/lib/model.js:1362:12)
    at async Strategy._verify (/Users/kimjoonyoung/SNS_Service/passport/kakaoStrategy.js:19:25)
---

**Comment by joonyy** [comment]
원인 : 현재 workbench를 통해 확인해본 결과, kakao 로그인이 된 계정의 이메일이 blackhound97@gmail.com임. 하지만, 현재 이미 이메일 값으로 blackhound97@gmail.com을 사용한 유저가 있음. 
---
sqlMessage: "Duplicate entry 'blackhound97@gmail.com' for key 'users.email'",
---
이와 같은 에러가 발생. users.email값이 겹쳐서 생기는 문제로 보임.
하지만, 카카오 로그아웃이 구현되지 않아 확인할 길이 없는 상태.
로그아웃 구현한 뒤 확인할 예정.
